### ISSUE TITLE
BM07: Oprette brugere

### ISSUE THREAD

**Issue by AGejr** [MarcusTheCode/2.-Semsterprojekt#12]

**Comment by KredeGC** [comment]
Review: Good... good. Let the hatred flow through you

**Comment by MarcusTheCode** [comment]
Ansvar bør ændres siden det ikke er dens ansvar at brugeren kommer med et kodeord eller brugernavn.
Databasen/datamanager sørger for at de er unikke.
Det er dens ansvar at oprette brugere.

**Comment by MarcusTheCode** [comment]
Prækondition skal være på dansk

**Comment by MarcusTheCode** [comment]
Din post kondition ville være mere i retning af: brugeren er oprettet.

**Comment by MarcusTheCode** [comment]
Er det ikke datamanageren der holder på brugere
